### ISSUE TITLE
Codecov

### ISSUE THREAD

**Issue by alecandido** [qiboteam/qiboml#13]
It seems that one of the most causes of failure is `CODECOV_TOKEN` access. Especially, it seems that since v4 tokenless upload is unsupported:

https://github.com/codecov/codecov-action/releases/tag/v4.0.0

Unfortunately, I can not access the repo settings in GitHub, but I believe we should just add the token, taken from here:
https://app.codecov.io/gh/qiboteam/qiboml/settings

@scarrazza

**Comment by alecandido** [comment]
@scarrazza it worked, perfectly
https://github.com/qiboteam/qiboml/actions/runs/8851612148/job/24399044447

@MatteoRobbiati whenever you can, confirm this as well, and then close the PR.

**Comment by MatteoRobbiati** [comment]
I can confirm, test are now passing. Thanks.
