### ISSUE TITLE
`qiboml` models modular vs monolithic approach

### ISSUE THREAD

**Issue by BrunoLiegiBastonLiegi** [qiboteam/qiboml#32]
Currently, #20 is implementing a modular approach to the construction of a model (variational circuit), in the sense that the circuit is seen as a sequence of layers, each one with its parameters, if any. To build the model, then, the user has to allocate the layers and pass them to the `QuantumModel`.

An alternative, more monolithic approach, would be to just ask the user to construct a circuit and pass it directly to the `QuantumModel`, providing, perhaps, some standard circuits as we are doing with the layers right now. The major advantage of this approach being that the parameters are all grouped together, making it easier to set them.

**Comment by alecandido** [comment]
Just a slightly different take: Qibo `Circuit`s are already modules, through their concatenation and `.on_qubits()` operations.

Though the `Circuit` modularity would be in charge of Qibo, and Qiboml would only integrate modules at the ML frameworks' level.
